FORMAT: 1A
HOST: http://api.startrack.com.au/shipping

# startrack

## Data Structures 

### Consignment
- consignmentId: string
- source: string
- IsAaE: bool
- ConsignmentStatus: string
- ConsignmentType: string
- ServiceCode: string
- DespatchDate: datetime
- EtaDate: datetime
- PayerAccountNumber: string
- PayerType: string
- DespatchId: string
- LastStatusDateTime: datetime
- ConsignmentStatusTime: string
- PodSignatoryName: string
- PodSignatureImage: string
- ContainsDangerousGoods: boolean
- Receiver: (ConsignmentReceiver)
- references: (References)

### ConsignmentSummary
- consignmentId: string
- consignmentStatus: string
- consignmentType: string
- serviceCode: string
- DeliveryDepot: string
- POD: string
- DespatchDate: datetime
- EtaDate: datetime
- LastStatusDateTime: datetime
- receiver: (ConsignmentReceiver)
- references: (References)
- trackingEvents: (TrackingEvents)
- lineItem: (LineItems)
- statusHistory: (UserStatusHistory)
- QualityControl: string

### TrackingEvents
- Consignment: string
- EventDateTime: string
- ScanDepot: string
- ScanDescription: datetime

### Scanner
- depotCode: string
- id: string
- type: string

### LineItems
- freightItems: (FreightItems)
- quantity: string

### DangerouseGoods
- interimDgPrinted: datetime
- quantity: string
- weight: decimal
- lockSeq: string

### FreightItems
- id: string

### StatusHistory
- userStatusHistory: (UserStatusHistory)
- dateTime: datetime
- signatoryName: string
- status: string
- depot: string

### UserStatusHistory
- dateTime: datetime
- status: string
- user: string

### References
- name: string
- value: string
- type: string
- printOnLabel: boolean
- priority: int

### CardLeftOptions
- allowRedeliver: boolean
- allowRedirect: boolean
- allowATL: boolean
- allowDepotCollection: boolean
- message: string
- type: string
- code: string

### Contact
- phone: string
- email: string

### ContactDetails
- claimantName: string
- claimantPhone: string
- claimantFax: string
- claimantEmail: string
- claimantAccount: string

### Receiver
- name: string
- contactDetail: (ReceiverContactDetail)

### ConsignmentReceiver
- ReceiverId: string
- ShortName: string
- Name: Collection of string
- AccountNumber: string
- ContactDetails: string
- contactDetail: (ReceiverContactDetailV2)

### ReceiverContactDetailV2
- Email: string
- Phone: string
- Mobile: string
- Fax: string
- address(ReceiverAddress)

### ReceiverContactDetail
- address(ReceiverAddress)

### ReceiverAddress
- AddressId: string
- AddressLines: Collection of string
- Suburb: string
- State: string
- Postcode: string
- Country: string

### WantsTo
- redeliver: boolean
- redirect: boolean

### CardLeft 
- consignment: string
- barcode: string
- contactPhone: string
- receiverName: string
- redeliveryDate: string
- WantsToRedeliver: boolean
- WantsToRedirect: boolean
- WantsToRedeliverATL: boolean
- RecieverCompanyName: string
- ReceiverAddress1: string
- ReceiverAddress2: string
- Suburb: string
- State: string
- Postcode: string
- IsAtl: boolean
- ATLLocationCard: string
- ATLLocationParcel: string
- RequestedByName: string
- ContactEmail: string

### Response
- type: string
- code: integer
- message: string

### CardLeftCheckReponse
- ResponseCode: string
- ResponseType: integer
- ResponseMessage: string

### PickupBookingResponse
- ResponseCode: string
- ResponseType: integer
- ResponseMessage: string
- BookingNumber: string

### CardLeftResponse
- ResponseType: string
- ResponseCode: integer
- ResponseMessage: string
- EnquiryId: string

### BookingResponse
- favouriteName: string
- bookingDetails: (BookingDetails)
- pickupDetails: (PickupDetails)
- freightDetails: (FreightDetails)
- ResponseCode: string
- ResponseMessage: string
- ResponseType: string

### ClaimItem
- name: string
- consignmentId: string

### LateDeliveryClaim
- claimItem: (ClaimItem)
- contactDetail: (ContactDetails)

### Booking
- CallerPhone: string
- Account: string
- Consignment: string
- ServiceType: string
- DangerousGoods: boolean
- CallerCompanyName: string
- CallerCompanyEmail: string
- PickupPhone: string
- PickupAddress1: string
- PickupAddress2: string
- PickupSuburb: string
- PickupCompanyName: string
- PickupName: string
- PickupState: string
- SavePickupDetails: boolean
- PickupPostcode: string
- PickupPointOfCollection: string
- PickupPrivateAddress: boolean
- PickupDate: string
- PickupReadyTime: string
- PickupCloseTime: string
- PickupConsignmentNoteRequired: boolean
- PickupSpecialInstructions: string
- IsControlledReturn: boolean
- IsBranchPrint: boolean
- freightItems: (RequestFreightDetails)

### RequestBookingDetails
- callerPhoneNbr: string
- accountId: string
- consignment: string
- serviceType: Collection of string
- dangerousGoods: boolean

### RequestPickupDetails
- Suburb: string
- State: string
- Postcode: string
- PointOfCollection: string
- PrivateAddress: boolean
- PickupDate: string
- ReadyTime: string
- CloseTime: string
- SpecialInstructions: string

### BookingDetails
- account: string
- callerPhoneNbr: string
- accountId: string
- consignment: string
- contactName: string
- companyName: string
- emailAddress: string
- serviceType: Collection of string
- serviceTypeDefault: string

### PickupDetails
- Suburb: string
- Postcode: string
- State: string
- PointOfCollection: string
- Contact: string
- PhoneNbr: string

### FreightDetails
- Description: string
- Quantity: string
- Weight: string
- Length: string
- Width: string
- Height: string
- HeaviestItemWeight: string
- TailgateRequired: boolean
- PackagingRequired: boolean
- SpecialHandlingRequired: boolean

### RequestFreightDetails
- Description: string
- Comments: string
- Quantity: string
- Weight: string
- Length: string
- Width: string
- Height: string
- HeaviestItemWeight: string
- TailgateRequired: boolean
- PackagingRequired: boolean
- SpecialHandlingRequired: boolean


### ReceiverDeliveryDetails
- receiverSuburb: string
- receiverState: string
- receiverPostCode: string

### SenderDeliveryDetails
- SenderSuburb: string
- SenderPostCode: string
- SenderState: string

### DeliveryTimeEstimateDetails
- serviceCode: string
- arrivalDate: string
- despatchDate: string
- receiverSuburb: string
- receiverState: string
- receiverPostCode: string
- SenderSuburb: string
- SenderPostCode: string
- SenderState: string

### DeliveryTimeEstimate
- eta: datetime
- etd: datetime

### CardLeftCheck
- consignment: string
- barcode: string
- receiverName: string
- receiverAddress1: string
- receiverAddress2: string
- receiverSuburb: string
- receiverState: string
- receiverPostcode: string
- wantsToRedeliver: bool
- wantsToRedirect: bool

### CardLeftDepot
- branchName: string
- collectionHours: string
- address1: string
- address2: string
- suburb: string
- postcode: string
- state: string
- instruction: string
- longitudeLatitude: string

### CardLeftDepotResponse
- ResponseType: string
- ResponseCode: integer
- ResponseMessage: string
- EnquiryId: string

## Consignments [/v1/consignments/{?ids}]
A comma separated list of `id` can be passed as parameter to fetch a list of Consignments.

+ Parameters
    + ids (required, string, `Z000001,Z000002`) ... String `id` of the Consignments to retrieve.
    

    
### List Consignments by consignment ids [GET]

+ Response 200 (application/json)
    + Attributes (Consignment)
  

## Consignments By Reference [/v1/consignmentsbyreferenceid/{id1%2cid2%2cidn}]
A comma separated list of `id` can be passed as parameter to fetch a list of Consignments by reference Id

+ Parameters
    + id (required, string, `ABCD1234,XYX1234`) ... String reference `id` of the Consignments to retrieve.

    
### List Consignments by reference ids [GET]

+ Response 200 (application/json)
    + Attributes (Consignment)
    

    
## Consignments Summary [/v1/consignmentsummary{?consignmentId,referenceId,searchType}]


+ Parameters
    + consignmentId (required, string)
    + referenceId (required,string) 
    + searchType (required,integer)

    
### Consignments Summary [GET]

+ Response 200 (application/json)
    + Attributes (ConsignmentSummary)
    

<!-- Note there is no GET /v1/consignment/{id} -->

## Card Left Options [/v1/cardleftoptions{?barcode,consignment}]
Object containing the options allowed when a client has been carded

+ Parameters
    + barcode or consignment


### Card Left Options [GET]

+ Response 200 (application/json)
    + Attributes (CardLeftOptions)
    

    
## Card Left [/v1/cardleft]
Allow client to create a action based on card left options

### Card Left [POST]

+ Request (application/json)
    + Attributes (CardLeft)   
            
+ Response 200 (application/json) 
    + Attributes (CardLeftResponse) 
    
    

## List Bookings [/v1/pickupbookinginfo/{?phoneNumber,accountId,consignmentId}]
This service allows the client get a list of pickup booking.

+ Parameters
    + phoneNumber (required, string)
    + accountId (required,string) 
    + consignmentId (required,string)

    
### List Bookings [GET]

+ Response 200 (application/json)
    + Attributes (BookingResponse)    
    

## Pickup Booking [/v1/pickupbooking]
Allow client to create a new booking

### Pickup Booking [POST]

+ Request (application/json)
    + Attributes (Booking)
    
+ Response 200 (application/json) 
    + Attributes (PickupBookingResponse)
    

    
## Delivery Time [/v1/deliverytimeestimate]
Allow client to get estimated delivery time

### Delivery Time Estimate [GET]

+ Request (application/json)
    + Attributes (DeliveryTimeEstimateDetails)
    
+ Response 200 (application/json) 
    + Attributes (DeliveryTimeEstimate)
    

    
## CardLeftCheck [/v1/cardleftcheck/{?consignment,barcode,receiverName,receiverAddress1,receiverAddress2,receiverSuburb,receiverState,receiverPostcode,wantsToRedeliver,wantsToRedirect}]
This service allows the check the cardleft

+ Parameters
    + consignment (required, string)
    + barcode (required,string) 
    + receiverName (required,string)
    + receiverAddress1 (required,string)
    + receiverAddress2 (required,string)
    + receiverSuburb (required,string)
    + receiverState (required,string)
    + receiverPostcode (required,string)
    + wantsToRedeliver (required,boolean)
    + wantsToRedirect (required,boolean)

### CardLeftCheck [GET]

+ Response 200 (application/json) 
    + Attributes (CardLeftCheckReponse)
    

    
## CardLeft Depots [/v1/cardleftdepots/{?consignment,barcode,contactPhone,conttactEmail,requestedName}]
This service allows the client get a list of cardleft depot.

+ Parameters
    + consignment (required, string)
    + barcode (required,string) 
    + contactPhone (required,string)
    + contactEmail (required,string)
    + requestedByName (required,string)
    

### CardLeft Depots [GET]

+ Response 200 (application/json)
    + Attributes (CardLeftDepotResponse)